name: 'Meditime Ertesito'
description: 'A Home Assistant addon'
version: '4.6.1'
slug: 'meditime_ertesito'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
options:
  logLevel: "info"
  users: []
  onePerDay: []
schema:
  logLevel: list(silent|fatal|error|warn|info|debug|trace)
  users:
    - id: int
      name: str
      email: email
  onePerDay:
    - str
