name: Run

on:
  workflow_dispatch: {}
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 */2 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
      - run: yarn start
