name: Run

on:
  workflow_dispatch: {}
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 */2 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - run: yarn start
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          READ_FROM_ENV: ${{ vars.READ_FROM_ENV }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          ONE_PER_DAY: ${{ secrets.ONE_PER_DAY }}
          USERS: ${{ secrets.USERS }}
          WARD_IDS: ${{ secrets.WARD_IDS }}
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          GOOGLE_AUTH_CREDENTIALS: ${{ secrets.GOOGLE_AUTH_CREDENTIALS }}
          MEDITIME_USERNAME: ${{ secrets.MEDITIME_USERNAME }}
          MEDITIME_PASSWORD: ${{ secrets.MEDITIME_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PW: ${{ secrets.SENDER_PW }}
